### PR TITLE
Added Anagram Checker

### PR DESCRIPTION
**Pull request by PiyushPawar17**

### CODE REVIEW

**Comment by sherxon** [comment]
is this the same as =>  https://github.com/sherxon/AlgoDS/blob/master/src/problems/easy/ValidAnagram.java ? :)

**Comment by PiyushPawar17** [comment]
I didn't knew that code was there. I just saw that Anagram code is not present in the algo directory so I made it on my own. By the way, my code is valid for 256 characters, not just for small alphabets. 😄

**Comment by sherxon** [comment]
cool) let's keep only one version of solutions unless the approaches are completely different.

**Comment by PiyushPawar17** [comment]
Also, I've not seen this whole repository. So this may happen again that some code is present in other directory and not in algo directory and I've send PR for same. 😅

**Comment by PiyushPawar17** [comment]
OK 👍 . Closing this PR.

**Pull request closed without merging**
